import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderMain from "./components/HeaderMain";
import Home from "./components/Home";
import TechItemsMenu from "./components/Products";
import Combobox from "./components/Combobox";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Maltec",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderMain/>
        <Home/>
        <Combobox/>
        
        {children}
        </body>
    </html>
  );
}
